CREATE DATABASE ARACLAR;

USE ARACLAR;

drop table islemler;
drop table araclar;
drop table musteriler;

CREATE TABLE musteriler (
MUSTERI_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ad VARCHAR(50)  NOT NULL,
soyad VARCHAR(50) NOT NULL,
adres VARCHAR(50) NOT NULL,
isyeri VARCHAR(50) NOT NULL,
unvan VARCHAR(50) NOT NULL,
tel VARCHAR(10) NOT NULL,
tc VARCHAR(11) NOT NULL
);


CREATE TABLE araclar (
SASI_NO INT PRIMARY KEY NOT NULL,
model VARCHAR(50) NOT NULL ,
yil INT NOT NULL,
renk VARCHAR(20) NOT NULL ,
fiyat DECIMAL(10, 2) NOT NULL ,
arac_durumu VARCHAR(50) NOT NULL ,
MUSTERI_ID INT,
FOREIGN KEY (MUSTERI_ID) REFERENCES musteriler(MUSTERI_ID)
);

CREATE TABLE islemler (
islem_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
MUSTERI_ID INT,
FOREIGN KEY (MUSTERI_ID) REFERENCES musteriler(MUSTERI_ID),
SASI_NO INT,
FOREIGN KEY (SASI_NO) REFERENCES araclar(SASI_NO)
)
